Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  DefaultContextTimeout: 60
  LogSavePath: storage/logs
  LogFileName: aoi
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8000/static
  UploadImageMaxSize: 30 # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
Email:
  Host: smtp.qq.com
  Port: 465
  UserName: xxxxx@qq.com
  Password:xxxxxx
  IsSSL: true
  From: xxxxxx@qq.com
  To:
    - xxxxxx@qq.com
JWT:
  Secret: eddycjy
  Issuer: blog-service
  Expire: 7200
Database:
  DBType: mysql
  UserName: Aoi
  Password: 123456
  Host: 101.43.161.75:3306
  DBName: aoi
  TablePrefix: article_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
